description: Prepares the repo for a typical CI job

name: Prepare

runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v3
      with:
        cache: "yarn"
        node-version: "18"
    - run: yarn install --frozen-lockfile
      shell: bash
